spring.application.name=app

spring.datasource.url=jdbc:postgresql://localhost:5432/personal_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=always
broker.ocr.tesseract-command=tesseract
broker.ocr.languages=rus+eng
